### ISSUE TITLE
Correct Indentation Marked as Wrong

### ISSUE THREAD

**Issue by mknecht** [hayd/pep8radius#81]
I have a file with a few changes. pep8, autopep8 and flake8 are all happy:

```
$ pep8 voicepoll.py
$ autopep8 --diff voicepoll.py
$ flake8 voicepoll.py
$
```

Still, pep8radius complains:

```
$ pep8radius --diff devel
--- voicepoll.py
+++ voicepoll.py
…
             "question": views_voice.dict_to_messages(
-                language)[0],
+                    language)[0],
```

If I fix the indentation as suggested, pep8, autopep8 and flake8 start complaining, and pep8radius is still not happy:

```
             "question": views_voice.dict_to_messages(
-                    language)[0],
+                        language)[0],
```

Any idea what the problem is? First thought it might be related to #2, but then autopep8 *is* happy.

Thanks for the tool! I'd love to plug it into our CI to support the Boyscout Principle in our team! :)

**Comment by hayd** [comment]
Thanks for the report. I'll have a play with this and see if I can reproduce and fix (I'm guessing it's an issue with the reindenting)!

**Comment by mknecht** [comment]
Could not reproduce anymore -_- Closing!
